### PR TITLE
adding support for multiple table types, tabular, tabularx and longtable

### PR DESCRIPTION
**Pull request by shepherdscientific**
To use the added feature set the desired Table Type under the table Ranges row in the settings tab

### CODE REVIEW

**Comment by caenrigen** [comment]
Hi! Thank you very much for your kind contribution 😊

I will try to review it during next week, for now please restore the `appsscript.json` it has important implications when publishing the add-on to the general public in the G Suite Marketplace.

Could you also specify if the `"runtimeVersion": "V8"` is really necessary? It might break some other parts of the code as I have experienced in the past with some other add-on

Cheers!

**Comment by shepherdscientific** [comment]
You're welcome. Thanks for building this excellent tools. appscript restored. 

In case it's helpful I'm using this sheet to test
https://docs.google.com/spreadsheets/d/1qeglOiXoEDVfLmIRIOR5NbuiJqT7HFlwiMCCYP66o10/edit?usp=sharing

**Comment by caenrigen** [comment]
Hi, @shepherdscientific !

I had a look at the code, unfortunately it is not quite ready for merging it into the master and providing it to the wide public in Google Sheets, but it can be improved and iterated over to get it to 1) not break anything and 2) comply to the (implicit) structure of the code. Apologies for not having an explicit contribution guide, time is scarce and donations very rare...

Regarding 1), your code breaks the "Manual" template, the following does not work anymore:

Screenshot 2020-09-28 at 18 27 41
Mind the "LaTeX alignment" in the cell in the left top corner:
Screenshot 2020-09-28 at 18 25 24

In order to accept the pull request the `longtable` type must be compatible with all Templates including the "Manual" one.

Regarding 2)
- please avoid, code repetitions in the code
- as well as hardcoding messages in the code (specially repeated ones), we don't have yet a proper way of dealing with code error unfortunately, but if you are including it please create a function in the `SettingsHardcode.js` to retrieve error messages, similar to what the code does with the Notes

- Only check the table type once and create alert at that point (happens at least for `create string.js`)
- Keep in mind language support... the specific messages for the beginning and continuation of the `longtable` table should be part of the spreadsheet (e.g. first cell of the first and last rows), so that users can specify it manually in other languages
- don't label with e.g. `tab:sheetName` there might be more than one table per sheet, it is not ok to force user to do so..., create instead another column in the setting sheet, I am fine with that

As a general comment and motivation for the observations above, I understand you have a specific need and I am very glad you were able to find the code and adapt it to your needs (congrats for that!), however, in order to share it with other users we need to take into account a fair amount of flexibility to satisfy the needs of most users as we have been striving to do so far!

I hope you can find the time to help bring this nice feature to all users!

If you have difficulties or questions feel free to drop them here (be as specific as possible!)

Cheers!

**Comment by shepherdscientific** [comment]
Hello @caenrigen

Thanks for your feedback. I've implemented changes you suggested with one small deviation, setting the Caption setting to default uses the sheetName. While still affording the user the option of setting a manual caption. Especially for longtables this makes sense since it is unlikely you will have two very large tables in the same sheet. Please have a look/test at your convenience.

**Comment by caenrigen** [comment]
Hi, @shepherdscientific !

Thank you once more for your efforts!!

I have worked on your code for some hours, changes are merged into master.
Very soon the changes should be available also in the G Suite Marketplace for the general public!

May the health be with you! Cheers

**Pull request closed without merging**
